modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="CC-BY-SA"

[[mods]] #mandatory
modId="scpff" #mandatory
version="0.0.1-1.19.4" #mandatory
displayName="SCP Fallen Foundation" #mandatory
logoFile="icon.png" #optional
credits="Thanks to Lucent, Willow, Phoillows, ConnorTron110, and Zeus" #optional
authors="YesMan" #optional
description='''
You are the last
They are free
do not mess up
'''

[[dependencies.scpff]]
modId="geckolib"
mandatory=true
versionRange="[4.1,)"
ordering="BEFORE"
side="BOTH"

[[dependencies.scpff]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.scpff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
